### ISSUE TITLE
WPS_YAML_FILE is not defined

### ISSUE THREAD

**Issue by reszel** [metabolism/wp-steroids#2]
Plugin could not be activated because it triggered a fatal error.

PS. From documentation:
When the bundle is installed, a default wordpress.yml is copied to /config/packages
PPS. There in no /config/packages under WP-root.

**Comment by jerome-barbato** [comment]
Hello ! 
This plugin is mostly designed to be used with the Wordpress bundle for Symfony but it should works also without.
You just have to define the absolute path to the yaml file in you wp-config.php
I will update the documentation asap, thank you for your comment
