### ISSUE TITLE
Table viewer CSV export is not guarded by admin login

### ISSUE THREAD

**Issue by markeasting** [metabolism/wp-steroids#4]
Hi Jerome,

It's possible to download CSV's from the table viewer when simply visiting `/edition/wp-admin/admin.php?page=table_event&action=export&id=1`, without being authenticated. 

There should definitely be a check wheter or not the user is logged in or not!

**Comment by jerome-barbato** [comment]
Hello, @markeasting, I've released a new version that fixes the issue.
https://github.com/jerome-barbato/wp-steroids/blob/4f3050abfc408e29d07d6d184894f56aa2840641/includes/extensions/class-config.php#L1002
